
DELETE http://localhost:3000/produtos/8

###

DELETE http://localhost:3000/usuarios/7

###

DELETE http://localhost:3000/mesa/delete/2

###

DELETE http://localhost:3000/formapagamento/delete/5

###

DELETE http://localhost:3000/comanda/delete/11

###

DELETE http://localhost:3000/itenscomanda/delete/2

###