

GET http://localhost:4000/produtos

###

GET http://localhost:4000/usuarios

###

GET http://localhost:3000/mesas

###


GET http://localhost:3000/formapagamento

###


GET http://localhost:3000/comanda

###


GET http://localhost:3000/itenscomanda

###
