
GET http://localhost:4000/comidas

###

GET http://localhost:4000/bebidas

###

GET http://localhost:4000/totaldia

###

GET http://localhost:4000/totalpagar

###

POST http://localhost:4000/totalproduto

{
    "produto": "Skol"
}

###

POST http://localhost:4000/totalpessoa

###